### ISSUE TITLE
Can't start c-lightning-REST as standalone or plugin

### ISSUE THREAD

**Issue by inpharmaticist** [Ride-The-Lightning/c-lightning-REST#179]
with
> node cl-rest.js

I get
> Error: Cannot find module 'node-cache'

I tried to install with
> npm install node-cache

And got
```
npm ERR! code ERR_SOCKET_CONNECTION_TIMEOUT
npm ERR! errno ERR_SOCKET_CONNECTION_TIMEOUT
npm ERR! request to https://registry.npmjs.org/node-cache failed, reason: Socket connection timeout
```

When trying to start as a plugin and the following in the cln config
> rest-port=3001
> rest-docport=4001
> rest-protocol=https
> rest-execmode=production
> rest-lnrpcpath=~/.lightning/bitcoin/lightning-rpc
> rest-rpc=*
> rest-domain=localhost
> rest-bind=::

I get
> Error: Cannot find module 'clightningjs'

Running Pop!_OS 22.04

**Comment by ShahanaFarooqui** [comment]
Npm install issue seems like npm server was temporarily down. It should work otherwise.

For plugin error: We had to rename the plugin file as “clrest.js” as while back. So please update your plugin file name to fix this issue.

Please note that running it as plugin will not resolve missing node-cache issue though. Installing it explicitly or a fresh install should fix that.

**Comment by inpharmaticist** [comment]
Thanks. I'm still getting the timeouts when trying to install node-cache. I'll try again tomorrow.

**Comment by ShahanaFarooqui** [comment]
`npm install node-cache`: I just tried installing it locally and it installed without any error. I am using node v18 though. However, it is something related to your setup not this particular project. 

plugin error: `clrest.js` is the correct file to add to your `config`. I am using it with `plugin=/home/[user]/workspace/c-lightning-REST/clrest.js` entry but setup is still trying to find the old file in `Error: Cannot find module 'clightningjs'`.

**Comment by inpharmaticist** [comment]
Made no changes and is working now :man_shrugging:
